version: '3.7'
services:
  frontend:
    image: glare-app-dev:dev
    container_name: glare-app-dev
    volumes:
      - /home/glare/glare-app-dev/config-dev.env:/app/.env
      - /home/glare/glare-app-dev/src:/app/src
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        EXPOSED_PORT: 3000
    ports:
      - "8091:3000"
    environment:
      env_file: config-dev.env
    networks:
      - appwrite
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
        - '444:443'
        - '3001:3000'
    restart: always
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/glare.cs.kent.edu/fullchain.pem:/etc/nginx/key.pem:ro
      - /etc/letsencrypt/live/glare.cs.kent.edu/privkey.pem:/etc/nginx/private.pem:ro
      - /var/www/glare.cs.kent.edu/public_html:/usr/share/nginx/html:ro
    depends_on:
      - frontend


networks:
    appwrite:
