version: '3.7'
services:
  frontend:
    image: glare-app-dev:dev
    container_name: glare-app-dev
    volumes:
      - /home/glare/glare-app-dev/config-dev.env:/app/.env
      - /home/glare/glare-app-dev/src:/app/src
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        REPOSITORY_URL: https://github.com/emjironal/glare-app
        BRANCH_NAME: fb5b92dec0686f03f74fef5038cb415ff48e01af
        EXPOSED_PORT: 8091
    ports:
      - "8091:8091"
    environment:
      env_file: config-dev.env
    networks:
      - appwrite
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
        - '444:443'
        - '3001:3000'
    restart: always
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/glare.cs.kent.edu/fullchain.pem:/etc/nginx/key.pem:ro
      - /etc/letsencrypt/live/glare.cs.kent.edu/privkey.pem:/etc/nginx/private.pem:ro
      - /var/www/glare.cs.kent.edu/public_html:/usr/share/nginx/html:ro
    depends_on:
      - frontend


networks:
    appwrite:
